### PR TITLE
Inherit from both `pydantic.BaseModel` and `sqlmodel.SQLModel`

### LINKED ISSUE #709: Inherit from both `pydantic.BaseModel` and `sqlmodel.SQLModel`
`SQLModel` is removed from common here https://github.com/fractal-analytics-platform/fractal-common/pull/65

### PR DESCRIPTION
**Pull request by ychiucco**
closes #709

### CODE REVIEW

**Comment by ychiucco** [comment]
As soon as https://github.com/fractal-analytics-platform/fractal-common/pull/65 is merged, switch `common` back to `main` (https://github.com/fractal-analytics-platform/fractal-server/pull/710/commits/28addf02ae35a640203dac0401e3277b918749e5)

**Comment by tcompa** [comment]
Great, thanks.

A few sanity checks would be useful, before merging:
1. Are the alembic-generated schemas identical to what is in `main`?
2. How does multiple inheritance depend on the parent-classes order? How does it handle overlapping attributes/methods?
3. Does the CI pass both on postgres and sqlite?

**Comment by tcompa** [comment]
> * Are the alembic-generated schemas identical to what is in `main`?

Yes.

> * How does multiple inheritance depend on the parent-classes order?

It does not.

> How does it handle overlapping attributes/methods?

There is only one that is "risky" (i.e., the `SQLModel.metadata` attribute), but nothing changes with this PR.

> * Does the CI pass both on postgres and sqlite?

Ongoing (postgres on github CI, sqlite locally). If it passes on both we can merge this.

**Comment by tcompa** [comment]
> Ongoing (postgres on github CI, sqlite locally). If it passes on both we can merge this.

Done.

**Pull request merged**
