### PR TITLE
New dataset history

### LINKED ISSUE #828: Fix bug in test fixtures
cc @mfranzon 

```python
from devtools import debug


async def test_work(
    MockCurrentUser,
    db,
    project_factory,
    workflow_factory,
    dataset_factory,
    job_factory,
    resource_factory,
    task_factory,
    tmp_path,
):
    async with MockCurrentUser(persist=True) as user:
        project = await project_factory(user)
        workflow = await workflow_factory(project_id=project.id)
        task = await task_factory(name="task")
        await workflow.insert_task(task_id=task.id, db=db)
        dataset1 = await dataset_factory(project)
        job = await job_factory(
            working_dir=tmp_path.as_posix(),
            project_id=project.id,
            input_dataset_id=dataset1.id,
            output_dataset_id=dataset1.id,
            workflow_id=workflow.id,
        )
        debug(job)


async def test_fail(
    MockCurrentUser,
    db,
    project_factory,
    workflow_factory,
    dataset_factory,
    job_factory,
    resource_factory,
    task_factory,
    tmp_path,
):
    async with MockCurrentUser(persist=True) as user:
        project = await project_factory(user)
        workflow = await workflow_factory(project_id=project.id)
        task = await task_factory(name="task")
        await workflow.insert_task(task_id=task.id, db=db)
        dataset1 = await dataset_factory(project, name="1")
        dataset2 = await dataset_factory(project, name="2")
        job = await job_factory(
            working_dir=tmp_path.as_posix(),
            project_id=project.id,
            input_dataset_id=dataset1.id,
            output_dataset_id=dataset1.id,
            workflow_id=workflow.id,
        )
        debug(job)
```

### LINKED ISSUE #829: Make sure that migration goes through when new required column is missing in current data
This is the case for `ApplyWorkflow.first_task_index`, which will be a new required column as of 1.3.5 - and existing DB obviously doesn't have values in there.

### PR DESCRIPTION
**Pull request by tcompa**
- [x] Update changelog
- [x] Use `history` for the new history property
- [x] Use `HISTORY_LEGACY` for the legacy version
- [x] Refactor handling of `JobExecutionError` and unkown errors, in runner, to use some new function
- [x] Remove new ApplyWorkflow properties, and make the `first/last_task_index` columns required
- [x] #829
- [x] #828
- [x] General clean up as suggested by @mfranzon 

Close #828 
Close #829

Postponed
- #830

### CODE REVIEW

**Comment by tcompa** [comment]
https://github.com/fractal-analytics-platform/fractal-server/pull/803/commits/a9edb5f9a4d495b3f1ae3e090471c97fdd950fa7 was needed for when the first task already fails, and then there  is no pre-existing `history_next` entry (either on disk or in the db).

**Comment by tcompa** [comment]
One currently-wrong behavior (to fix):
* Multiple TaskExecutionError-failing executions of a workflow with given I/O datasets result in the correct `dataset['history_next']` attribute for output dataset (with number of items increasing by one at each new attempt)
* A successful execution erases the current history before appending a new item to it.

**Comment by tcompa** [comment]
> One currently-wrong behavior (to fix):
> 
>     * Multiple TaskExecutionError-failing executions of a workflow with given I/O datasets result in the correct `dataset['history_next']` attribute for output dataset (with number of items increasing by one at each new attempt)
> 
>     * A successful execution erases the current history before appending a new item to it.

Explanation:
`process_workflow` is never aware of the existing metadata for the _output_ dataset; when `process_workflow` returns, its output is used to overwrite `output_dataset.meta`.

Solution:
`output_dataset.meta = await process_workflow(...)` should be replaced with a slightly more complex code block, which stores the function output and then merges it into `output_dataset.meta`.

**Comment by tcompa** [comment]
> > One currently-wrong behavior (to fix):
> > ```
> > * Multiple TaskExecutionError-failing executions of a workflow with given I/O datasets result in the correct `dataset['history_next']` attribute for output dataset (with number of items increasing by one at each new attempt)
> > 
> > * A successful execution erases the current history before appending a new item to it.
> > ```
> 
> Explanation: `process_workflow` is never aware of the existing metadata for the _output_ dataset; when `process_workflow` returns, its output is used to overwrite `output_dataset.meta`.
> 
> Solution: `output_dataset.meta = await process_workflow(...)` should be replaced with a slightly more complex code block, which stores the function output and then merges it into `output_dataset.meta`.

Fixed with https://github.com/fractal-analytics-platform/fractal-server/pull/803/commits/ac324e6e171fe85a4b116b50b0b7dce6d7635094.

**Comment by tcompa** [comment]
For the record: real-life tests of the `get_workflowtask_status` endpoint show that it's fully bugged. I'll move on towards some actual CI test.

**Review by mfranzon — COMMENTED** [review]
Clean `# type: ignore[import]`

**Comment by tcompa** [comment]
> Clean `# type: ignore[import]`

This should be done with https://github.com/fractal-analytics-platform/fractal-server/pull/803/commits/cc6f4c82930893baff548a5d4c0e58b4102c99b1

**Pull request merged**
