### PR TITLE
Deprecate use of v1 tasks within v2 workflows

### LINKED ISSUE #1722: Fix migration for sqlite
A model change like
```diff
diff --git a/fractal_server/app/models/v2/workflowtask.py b/fractal_server/app/models/v2/workflowtask.py
index 75e0f28b2..32f64215a 100644
--- a/fractal_server/app/models/v2/workflowtask.py
+++ b/fractal_server/app/models/v2/workflowtask.py
@@ -8,7 +8,6 @@ from sqlmodel import Field
 from sqlmodel import Relationship
 from sqlmodel import SQLModel
 
-from ..v1.task import Task
 from .task import TaskV2
 
 
@@ -37,13 +36,6 @@ class WorkflowTaskV2(SQLModel, table=True):
     )
 
     # Task
-    is_legacy_task: bool
     task_type: str
-    task_id: Optional[int] = Field(foreign_key="taskv2.id")
-    task: Optional[TaskV2] = Relationship(
-        sa_relationship_kwargs=dict(lazy="selectin")
-    )
-    task_legacy_id: Optional[int] = Field(foreign_key="task.id")
-    task_legacy: Optional[Task] = Relationship(
-        sa_relationship_kwargs=dict(lazy="selectin")
-    )
+    task_id: int = Field(foreign_key="taskv2.id")
+    task: TaskV2 = Relationship(sa_relationship_kwargs=dict(lazy="selectin"))
```
generates a migration script like
```python

# revision identifiers, used by Alembic.
revision = "a75703146940"
down_revision = "5bf02391cfef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflowtaskv2", "task_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        "fk_workflowtaskv2_task_legacy_id_task",
        "workflowtaskv2",
        type_="foreignkey",
    )
    op.drop_column("workflowtaskv2", "task_legacy_id")
    op.drop_column("workflowtaskv2", "is_legacy_task")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflowtaskv2",
        sa.Column("is_legacy_task", sa.BOOLEAN(), nullable=False),
    )
    op.add_column(
        "workflowtaskv2",
        sa.Column("task_legacy_id", sa.INTEGER(), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflowtaskv2_task_legacy_id_task",
        "workflowtaskv2",
        "task",
        ["task_legacy_id"],
        ["id"],
    )
    op.alter_column(
        "workflowtaskv2", "task_id", existing_type=sa.INTEGER(), nullable=True
    )
```
which is not valid for sqlite in our current configuration
```
NotImplementedError: No support for ALTER of constraints in SQLite dialect. Please refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
```

### PR DESCRIPTION
**Pull request by tcompa**
This cannot be merged&released until we verify that production instances do not include any such task (see script in #1712).

closes #1722

## Checklist before merging
- [x] Update #1722 
- [x] Test migration failure when there was still some legacy task in v2 workflows
- [x] I checked all `FIXME 1712` entries
- [x] I added an appropriate entry to `CHANGELOG.md`
- [x] I added logging to new code - if appropriate.
- [x] I merged `main` into the current branch.

### CODE REVIEW

**Comment by tcompa** [comment]
Note that the CI currently fails because of sqlite:
```
NotImplementedError: No support for ALTER of constraints in SQLite dialect. Please refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
```

**Comment by jluethi** [comment]
For my understanding: Do we need to remove V1 legacy tasks from Fractal server or can we still have them there in old workflows, just without the possibility of running them?

If we go for an option where we need to first remove them from all workflows, I think it's doable. There are some 30-40 workflows on the Liberali server with V1 legacy tasks, we could manually replace them with the V2 version of the task in each workflow (e.g. download the json parameters of the task, add the new version, upload the parameters there)

**Comment by tcompa** [comment]
> For my understanding: Do we need to remove V1 legacy tasks from Fractal server or can we still have them there in old workflows, just without the possibility of running them?

The first one you said: we cannot have V1 tasks linked to V2 tasks any more. Because this action is required, we are completing this PR but we will not merge&release it until the relevant instances are ready.

> If we go for an option where we need to first remove them from all workflows, I think it's doable. There are some 30-40 workflows on the Liberali server with V1 legacy tasks, we could manually replace them with the V2 version of the task in each workflow (e.g. download the json parameters of the task, add the new version, upload the parameters there)

Yes, this would the preferred approach. The script from #1712 should let you identify the workflows quickly, but then the legacy-task replacement has to be manual. We can also prepare a script for performing this kind of replacements, if that is useful, although it's TBD whether it would actually save us time.

**Comment by jluethi** [comment]
> Yes, this would the preferred approach. The script from https://github.com/fractal-analytics-platform/fractal-server/issues/1712 should let you identify the workflows quickly, but then the legacy-task replacement has to be manual. We can also prepare a script for performing this kind of replacements, if that is useful, although it's TBD whether it would actually save us time.

I think we'll be able to do this manually within an hour or 2, so no need for a script. It's not optimal that we have to change old workflows, but I agree that the trade-off here is worth it.

I'll do this at FMI & can also handle it at UZH once the Ilastik task has been tested & verified :)

**Comment by jluethi** [comment]
All legacy tasks in V2 workflows have now been removed from both servers :)

**Comment by ychiucco** [comment]
The migration added by this PR will fail ([here](https://github.com/fractal-analytics-platform/fractal-server/blob/00950261ec018063fba5cb49be6781aa2323ba99/fractal_server/migrations/versions/501961cfcd85_remove_link_between_v1_and_v2_tasks_.py#L22-L25)) if performed on a database with a legacy Task in a WorkflowV2.

---

Test:

- Switch to `main` and create a DB such that
```sql
select is_legacy_task from workflowtaskv2;

is_legacy_task
----------------
 f
 t
(2 rows)
```

- Switch to `1712-on-hold-deprecate-use-of-v1-tasks-within-v2-workflows` and run `fractalctl set-db`:
```
WARNING:root:FRACTAL_TASKS_DIR="tasks" is not an absolute path; converting it to "/Users/yuri/Desktop/eXact/fractal/fractal-server/tasks"
WARNING:root:FRACTAL_RUNNER_WORKING_BASE_DIR="artifacts" is not an absolute path; converting it to "/Users/yuri/Desktop/eXact/fractal/fractal-server/artifacts"
START: Run alembic.config, with argv=['-c', '/Users/yuri/Desktop/eXact/fractal/fractal-server/fractal_server/alembic.ini', 'upgrade', 'head']
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 091b01f51f88 -> d9a140db5d42, Remove link between v1 and v2 tasks/workflowtasks tables
Traceback (most recent call last):
...
...
asyncpg.exceptions.NotNullViolationError: column "task_id" of relation "workflowtaskv2" contains null values

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
...
...

sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: column "task_id" of relation "workflowtaskv2" contains null values
[SQL: ALTER TABLE workflowtaskv2 ALTER COLUMN task_id SET NOT NULL]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

- Remove the legacy Task from the WorkflowV2, i.e.
```sql
select is_legacy_task from workflowtaskv2;

is_legacy_task
----------------
 f
(1 row)
```

- Run again `fractalctl set-db`:
```
WARNING:root:FRACTAL_TASKS_DIR="tasks" is not an absolute path; converting it to "/Users/yuri/Desktop/eXact/fractal/fractal-server/tasks"
WARNING:root:FRACTAL_RUNNER_WORKING_BASE_DIR="artifacts" is not an absolute path; converting it to "/Users/yuri/Desktop/eXact/fractal/fractal-server/artifacts"
START: Run alembic.config, with argv=['-c', '/Users/yuri/Desktop/eXact/fractal/fractal-server/fractal_server/alembic.ini', 'upgrade', 'head']
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 091b01f51f88 -> d9a140db5d42, Remove link between v1 and v2 tasks/workflowtasks tables
END: alembic.config

START: Default group creation
END: Default group creation

START: First user creation
END: First user creation
```

**Review by ychiucco — APPROVED** [review]

**Pull request merged**
