### PR TITLE
617 review use of fractal logging level

### PR DESCRIPTION
**Pull request by tcompa**

### CODE REVIEW

**Comment by tcompa** [comment]
The first bunch of commits actually addresses #268, going from logs like
```
Start background task collection
Status: installing
Status: collecting
Status: finalising
Status: OK
Background task collection completed successfully
```
to more detailed logs like
```
Start background task collection
Status: installing
Creating venv and installing package
Subprocess call to: /home/tommaso/.cache/pypoetry/virtualenvs/fractal-server-cyevISt_-py3.10/bin/python -m venv venv


Subprocess call to: /tmp/pytest-of-tommaso/pytest-17/server_folder0/fractal_tasks_dir/test_user_30/fractal_tasks_dummy0.1.0/venv/bin/pip install --upgrade pip
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.0.2)
Collecting pip
  Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-23.0.1


Subprocess call to: /tmp/pytest-of-tommaso/pytest-17/server_folder0/fractal_tasks_dir/test_user_30/fractal_tasks_dummy0.1.0/venv/bin/pip install /tmp/pytest-of-tommaso/pytest-17/fractal-tasks-dummy0/dist/fractal_tasks_dummy-0.1.0-py3-none-any.whl
Processing /tmp/pytest-of-tommaso/pytest-17/fractal-tasks-dummy0/dist/fractal_tasks_dummy-0.1.0-py3-none-any.whl
Collecting pydantic<2.0.0,>=1.10.1
  Using cached pydantic-1.10.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: typing-extensions, pydantic, fractal-tasks-dummy
Successfully installed fractal-tasks-dummy-0.1.0 pydantic-1.10.7 typing-extensions-4.5.0


Subprocess call to: /tmp/pytest-of-tommaso/pytest-17/server_folder0/fractal_tasks_dir/test_user_30/fractal_tasks_dummy0.1.0/venv/bin/pip show fractal_tasks_dummy
Name: fractal-tasks-dummy
Version: 0.1.0
Summary: 
Home-page: 
Author: Jacopo Nespolo
Author-email: jacopo.nespolo@exact-lab.it
License: 
Location: /tmp/pytest-of-tommaso/pytest-17/server_folder0/fractal_tasks_dir/test_user_30/fractal_tasks_dummy0.1.0/venv/lib/python3.10/site-packages
Requires: pydantic
Required-by: 


Loading task manifest
Loaded task manifest
Status: collecting
Status: finalising
```

**Comment by jluethi** [comment]
While we're at this: Can we include time stamps into the logs that are shown on the Fractal server side? Currently, I often see this when I log in to a server, but would be good to know if a user was submitting requests 5 minutes or 2 weeks ago :)

Screenshot 2023-04-14 at 10 14 01

**Comment by tcompa** [comment]
> While we're at this: Can we include time stamps into the logs that are shown on the Fractal server side? Currently, I often see this when I log in to a server, but would be good to know if a user was submitting requests 5 minutes or 2 weeks ago :)

I've already added timestamps for all fractal-server logs (as part of this PR), but the ones in the screenshot are uvicorn logs, which we do not define/configure ourselves.

A future refactor (which we were already discussing this morning) will concern the integration of three logging levels (uvicorn/gunicorn, fastapi, fractal-server). This will for sure be useful in order to have a homogeneous format (including time stamps), but also because we'll have to move towards a different setup, where logs are written (also?) to file, and files are handled in the proper way with rotation (https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler).

**Comment by jluethi** [comment]
Great, thanks for the context! :)

**Pull request merged**
