### PR TITLE
Fix sqlite "database is locked" error

### PR DESCRIPTION
**Pull request by zonia3000**
## Checklist before merging
- [x] I added an appropriate entry to `CHANGELOG.md`

This solves the `sqlite3.OperationalError: database is locked` that appears sometimes when using sqlite.

Reference: https://www.sqlite.org/wal.html

> WAL provides more concurrency as readers do not block writers and a writer does not block readers. Reading and writing can proceed concurrently.

### CODE REVIEW

**Comment by tcompa** [comment]
Thanks Sonia! We'll review this asap.

Possibly related to multiple past issues:
* https://github.com/fractal-analytics-platform/fractal-server/issues/647
* https://github.com/fractal-analytics-platform/fractal-server/issues/854
* https://github.com/fractal-analytics-platform/fractal-server/issues/649

**Comment by tcompa** [comment]
For the record, the CI also passes locally - where I use sqlite (while the GitHub action uses postgres).

**Comment by mfranzon** [comment]
I think we can merge this PR. 

Locally I have no problem, CI works fine with sqlite. 

Looking at the Disadvantages section in the [docs](https://sqlite.org/wal.html), seems that we are safe. The only thing I want to mention i point 2 
> All processes using a database must be on the same host computer; WAL does not work over a network filesystem.

Which can be a potential problem if we want to use sqlite on a network (fractal-containers) which could be easily solved via docker volumes. BUT at the moment we are happy with postgres so, the sqlite usage is strictly related to local testing.

**Review by mfranzon — APPROVED** [review]

**Comment by tcompa** [comment]
Thanks Marco for the review. Maybe what we can add (after #891 is merged) is a test of `set_db` which always runs with SQLite (even when the postgres extra is installed), so that we would be also testing these new lines.

**Comment by tcompa** [comment]
> Which can be a potential problem if we want to use sqlite on a network (fractal-containers) which could be easily solved via docker volumes. BUT at the moment we are happy with postgres

Agreed, not an issue.

> the sqlite usage is strictly related to local testing.

Local testing or local demo-ing. But we always print a very clear warning saying the SQLite is not fully supported.

**Comment by tcompa** [comment]
> Thanks Marco for the review. Maybe what we can add (after #891 is merged) is a test of `set_db` which always runs with SQLite (even when the postgres extra is installed), so that we would be also testing these new lines.

#891 is on hold, therefore this test should be included within the current setup.

**Comment by tcompa** [comment]
> therefore this test should be included within the current setup.

Implemented with #915. If the CI passes, this is ready to merge

**Comment by tcompa** [comment]
Before #915:
> 57.14% of new lines are covered.

After #915:
> 100% of new lines are covered.

Thanks @zonia3000 and @ychiucco! I'm now merging this one.

**Pull request merged**
